var jobDataArr=[
    // front end developer
    { profile: "Full Stack Developer", company:"Google", experience:"1 - 3 years",salary:" ₹ 1,75,0000 - 2,50,0000 P.A.",location:"Mumbai Suburban, Thane, Mumbai (All Areas)",discription:"In-depth knowledge of Reactjs / Vue.JS/ Angular Good knowledge of HTML, HTML5, CSS, BOOTSTRAP, JAVASCRIPT & JQUERY."},
    { profile:"Product Manager",company:"Amazon", experience:" 1 - 3 years",salary:" Not Disclosed",location:"Bangalore/Bengaluru, Remote",discription:"In-depth knowledge of Reactjs / Vue.JS/ Angular Good knowledge of HTML, HTML5, CSS, BOOTSTRAP, JAVASCRIPT & JQUERY."},
    { profile:"Quality Engineer",company:"Meta", experience:"1 - 2 years",salary:" ₹ 20,00,000 - 40,00,000 P.A.",location:" Hyderabad/Secunderabad( Madhapur )",discription:"In-depth knowledge of Reactjs / Vue.JS/ Angular Good knowledge of HTML, HTML5, CSS, BOOTSTRAP, JAVASCRIPT & JQUERY."},
    { profile:"Software Development Engineer-I",company:"Apple", experience:" 0 - 3 years",salary:" ₹ 20,25,000 - 40,00,000 P.A.",location:"New Delhi",discription:"In-depth knowledge of Reactjs / Vue.JS/ Angular Good knowledge of HTML, HTML5, CSS, BOOTSTRAP, JAVASCRIPT & JQUERY."},
    { profile:"Design Engineer",company:" TATA Motors", experience:" 1 - 4 years",salary:"₹ 6,00,000 - 8,00,000 P.A.",location:"Pune, Mumbai (All Areas) (WFH during Covid)",discription:"In-depth knowledge of Reactjs / Vue.JS/ Angular Good knowledge of HTML, HTML5, CSS, BOOTSTRAP, JAVASCRIPT & JQUERY."},
    
    // // //Digital Marketing
    { profile:"Digital Marketing Specialists",company:"viral mafia - Digital Marketing Agency", experience:" 1 - 3 years",salary:" Not Disclosed",location:"Bangalore/Bengaluru, Remote",discription:"End to end campaign management (executing,monitoring,evaluating,and optimizing campaign performance to generate maximum leads"},
    { profile:"Digital Marketing Executive",company:"Techizer Tech Solutions Private Limited", experience:"1 - 5 years",salary:" Not Disclosed",location:"Mumbai, Borivali",discription:"End to end campaign management (executing,monitoring,evaluating,and optimizing campaign performance to generate maximum leads"},
    { profile:"Digital Marketing Manager",company:"Aarrrmor Digital", experience:"1 - 5 years",salary:" ₹ 1,00,000 - 2,25,000 P.A.",location:"Hyderabad/Secunderabad, Chennai, Bangalore/Bengaluru",discription:"End to end campaign management (executing,monitoring,evaluating,and optimizing campaign performance to generate maximum leads"},
    { profile:" Jr. Digital Marketing Executive",company:" Xenia Consulting", experience:" 0 - 1 years",salary:" ₹ 1,25,000 - 3,00,000 P.A.",location:"Pune( Bavdhan ) (WFH during Covid)",discription:"End to end campaign management (executing,monitoring,evaluating,and optimizing campaign performance to generate maximum leads"},
    { profile:"Digital Marketing Specialists",company:"KMR Living", experience:"1 - 5 years",salary:" Not Disclosed",location:"New Delhi( New Friends Colony )",discription:"End to end campaign management (executing,monitoring,evaluating,and optimizing campaign performance to generate maximum leads"},

    
    // // need update
    // { "profile":"Digital Marketing Specialists","company":"KMR Living", "experience":"1 - 5 years","salary":" Not Disclosed","location":"New Delhi( New Friends Colony )","discription":"End to end campaign management (executing,monitoring,evaluating,and optimizing campaign performance to generate maximum leads"},
    // { "profile":"Digital Marketing Specialists","company":"KMR Living", "experience":"1 - 5 years","salary":" Not Disclosed","location":"New Delhi( New Friends Colony )","discription":"End to end campaign management (executing,monitoring,evaluating,and optimizing campaign performance to generate maximum leads"},
    // { "profile":"Digital Marketing Specialists","company":"KMR Living", "experience":"1 - 5 years","salary":" Not Disclosed","location":"New Delhi( New Friends Colony )","discription":"End to end campaign management (executing,monitoring,evaluating,and optimizing campaign performance to generate maximum leads"},
    // { "profile":"Digital Marketing Specialists","company":"KMR Living", "experience":"1 - 5 years","salary":" Not Disclosed","location":"New Delhi( New Friends Colony )","discription":"End to end campaign management (executing,monitoring,evaluating,and optimizing campaign performance to generate maximum leads"},
    // { "profile":"Digital Marketing Specialists","company":"KMR Living", "experience":"1 - 5 years","salary":" Not Disclosed","location":"New Delhi( New Friends Colony )","discription":"End to end campaign management (executing,monitoring,evaluating,and optimizing campaign performance to generate maximum leads"},

    // //need update
    // { "profile":"Digital Marketing Specialists","company":"KMR Living", "experience":"1 - 5 years","salary":" Not Disclosed","location":"New Delhi( New Friends Colony )","discription":"End to end campaign management (executing,monitoring,evaluating,and optimizing campaign performance to generate maximum leads"},
    // { "profile":"Digital Marketing Specialists","company":"KMR Living", "experience":"1 - 5 years","salary":" Not Disclosed","location":"New Delhi( New Friends Colony )","discription":"End to end campaign management (executing,monitoring,evaluating,and optimizing campaign performance to generate maximum leads"},
    // { "profile":"Digital Marketing Specialists","company":"KMR Living", "experience":"1 - 5 years","salary":" Not Disclosed","location":"New Delhi( New Friends Colony )","discription":"End to end campaign management (executing,monitoring,evaluating,and optimizing campaign performance to generate maximum leads"},
    // { "profile":"Digital Marketing Specialists","company":"KMR Living", "experience":"1 - 5 years","salary":" Not Disclosed","location":"New Delhi( New Friends Colony )","discription":"End to end campaign management (executing,monitoring,evaluating,and optimizing campaign performance to generate maximum leads"},
    // { "profile":"Digital Marketing Specialists","company":"KMR Living", "experience":"1 - 5 years","salary":" Not Disclosed","location":"New Delhi( New Friends Colony )","discription":"End to end campaign management (executing,monitoring,evaluating,and optimizing campaign performance to generate maximum leads"},


    // //need update
    // { "profile":"Digital Marketing Specialists","company":"KMR Living", "experience":"1 - 5 years","salary":" Not Disclosed","location":"New Delhi( New Friends Colony )","discription":"End to end campaign management (executing,monitoring,evaluating,and optimizing campaign performance to generate maximum leads"},
    // { "profile":"Digital Marketing Specialists","company":"KMR Living", "experience":"1 - 5 years","salary":" Not Disclosed","location":"New Delhi( New Friends Colony )","discription":"End to end campaign management (executing,monitoring,evaluating,and optimizing campaign performance to generate maximum leads"},
    // { "profile":"Digital Marketing Specialists","company":"KMR Living", "experience":"1 - 5 years","salary":" Not Disclosed","location":"New Delhi( New Friends Colony )","discription":"End to end campaign management (executing,monitoring,evaluating,and optimizing campaign performance to generate maximum leads"},
    // { "profile":"Digital Marketing Specialists","company":"KMR Living", "experience":"1 - 5 years","salary":" Not Disclosed","location":"New Delhi( New Friends Colony )","discription":"End to end campaign management (executing,monitoring,evaluating,and optimizing campaign performance to generate maximum leads"},
    // { "profile":"Digital Marketing Specialists","company":"KMR Living", "experience":"1 - 5 years","salary":" Not Disclosed","location":"New Delhi( New Friends Colony )","discription":"End to end campaign management (executing,monitoring,evaluating,and optimizing campaign performance to generate maximum leads"},
    
]
localStorage.setItem("jobDetail",JSON.stringify(jobDataArr));
// localStorage.setItem("Newjob",JSON.stringify("abcde"))